const box = document.querySelector('.box')
const breadTop = document.createElement('div')
breadTop.classList.add('bread-top')
const seeds= document.createElement('div')
const seeds2= document.createElement('div')
seeds.classList.add('seeds')
seeds2.classList.add('seeds2')
box.append(breadTop)
breadTop.append(seeds)
breadTop.append(seeds2)
const element= document.createElement('span')
box.append(element)
const breadBottom= document.createElement('div')
breadBottom.classList.add('bread-bottom')
box.append(breadBottom)